// This file is generated by snap.py.  Do not edit.
window.SCREENSHOTS = [
  { name: "/404.html", slug: "404", hasOld: true },
  { name: "/docs/changelog.html", slug: "docs__changelog", hasOld: false },
  { name: "/docs/configuration/configyml.html", slug: "docs__configuration__configyml", hasOld: true },
  { name: "/docs/configuration/debug.html", slug: "docs__configuration__debug", hasOld: true },
  { name: "/docs/configuration/frontmatter.html", slug: "docs__configuration__frontmatter", hasOld: true },
  { name: "/docs/debug.html", slug: "docs__debug", hasOld: true },
  { name: "/docs/demo-pages/deepersection/test-page.html", slug: "docs__demo-pages__deepersection__test-page", hasOld: true },
  { name: "/docs/demo-pages/index.html", slug: "docs__demo-pages__index", hasOld: true },
  { name: "/docs/demo-pages/test-page.html", slug: "docs__demo-pages__test-page", hasOld: true },
  { name: "/docs/dev.html", slug: "docs__dev", hasOld: true },
  { name: "/docs/faqs.html", slug: "docs__faqs", hasOld: true },
  { name: "/docs/index.html", slug: "docs__index", hasOld: true },
  { name: "/docs/jekyll.html", slug: "docs__jekyll", hasOld: true },
  { name: "/docs/quickstart.html", slug: "docs__quickstart", hasOld: true },
  { name: "/index.html", slug: "index", hasOld: true },
  { name: "/search.html", slug: "search", hasOld: true },
];
